Repository aca24/UKS, pull requests merged in 2022-02, with the labels that each got.

#42 Feature security
  pom.xml
  src/main/java/com/github/minigithub/MinigithubApplication.java
  src/main/java/com/github/minigithub/config/WebConfig.java
  src/main/java/com/github/minigithub/config/WebConfigAdapt.java
  src/main/java/com/github/minigithub/config/WebSecurityConfiguration.java
  src/main/java/com/github/minigithub/controller/AuthenticationController.java
  src/main/java/com/github/minigithub/controller/LabelController.java
  src/main/java/com/github/minigithub/dto/UserLoginDTO.java
  src/main/java/com/github/minigithub/dto/UserTokenStateDTO.java
  src/main/java/com/github/minigithub/model/Role.java
  src/main/java/com/github/minigithub/model/User.java
  src/main/java/com/github/minigithub/security/TokenUtils.java
  src/main/java/com/github/minigithub/security/auth/RestAuthenticationEntryPoint.java
  src/main/java/com/github/minigithub/security/auth/TokenAuthenticationFilter.java
  src/main/java/com/github/minigithub/security/auth/TokenBasedAuthentication.java
  src/main/java/com/github/minigithub/service/CustomUserDetailsService.java
  src/main/resources/application.properties
  src/main/resources/import.sql
Labels: enhancement

#45 Added env variables
  .github/workflows/maven.yml
  pom.xml
  src/main/resources/application-build.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-staging.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: configure, devops

#47 Replace LocalDateTime with Date
  src/main/java/com/github/minigithub/dto/CommentDTO.java
  src/main/java/com/github/minigithub/dto/EventDTO.java
  src/main/java/com/github/minigithub/dto/LabelApplicationDTO.java
  src/main/java/com/github/minigithub/dto/StateChangeDTO.java
  src/main/java/com/github/minigithub/model/Comment.java
  src/main/java/com/github/minigithub/model/Event.java
  src/main/java/com/github/minigithub/model/LabelApplication.java
  src/main/java/com/github/minigithub/model/StateChange.java
Labels: bug

#48 labelApplication attribute setting
  src/main/java/com/github/minigithub/mapper/LabelMapper.java
Labels: bug

#49 added fetch type for tasks in milestone
  src/main/java/com/github/minigithub/model/Milestone.java
  src/main/java/com/github/minigithub/model/Task.java
  src/main/resources/import.sql
Labels: bug

#50 mapped gitRepo and developers
  src/main/java/com/github/minigithub/dto/ProjectDTO.java
  src/main/java/com/github/minigithub/mapper/GitRepoMapper.java
  src/main/java/com/github/minigithub/mapper/ProjectMapper.java
  src/main/java/com/github/minigithub/service/implementation/ProjectServiceImplementation.java
  src/main/resources/import.sql
Labels: bug

#52 new user registration
  src/main/java/com/github/minigithub/controller/AuthenticationController.java
  src/main/java/com/github/minigithub/service/UserService.java
Labels: enhancement

#53 Controller-front mapping calls
  src/main/java/com/github/minigithub/controller/CommentController.java
  src/main/java/com/github/minigithub/controller/EventController.java
  src/main/java/com/github/minigithub/controller/LabelApplicationController.java
Labels: enhancement

#54 deleting entities updated
  src/main/java/com/github/minigithub/controller/ProjectController.java
  src/main/java/com/github/minigithub/dto/TaskDTO.java
  src/main/java/com/github/minigithub/model/Project.java
  src/main/java/com/github/minigithub/model/Task.java
  src/main/java/com/github/minigithub/repository/LabelRepository.java
  src/main/java/com/github/minigithub/repository/MilestoneRepository.java
  src/main/java/com/github/minigithub/service/ProjectService.java
  src/main/java/com/github/minigithub/service/implementation/LabelServiceImplementation.java
  src/main/java/com/github/minigithub/service/implementation/MilestoneServiceImplementation.java
  src/main/java/com/github/minigithub/service/implementation/ProjectServiceImplementation.java
  src/main/resources/import.sql
Labels: enhancement

#55 removed parent event from data sql, watched as apstract class
  src/main/resources/import.sql
Labels: invalid

#56 removing developers from project
  src/main/java/com/github/minigithub/controller/ProjectController.java
  src/main/java/com/github/minigithub/repository/ProjectRepository.java
  src/main/java/com/github/minigithub/service/ProjectService.java
  src/main/java/com/github/minigithub/service/implementation/ProjectServiceImplementation.java
  src/main/resources/import.sql
Labels: enhancement

#57 set id of the comments in sqript
  src/main/resources/import.sql
Labels: enhancement, configure

#58 Feature controllers update
  src/main/java/com/github/minigithub/controller/CommentController.java
  src/main/java/com/github/minigithub/controller/EventController.java
  src/main/java/com/github/minigithub/controller/LabelApplicationController.java
  src/main/java/com/github/minigithub/service/CommentService.java
  src/main/java/com/github/minigithub/service/EventService.java
  src/main/java/com/github/minigithub/service/LabelApplicationService.java
  src/main/java/com/github/minigithub/service/implementation/CommentServiceImplementation.java
  src/main/java/com/github/minigithub/service/implementation/EventServiceImplementation.java
  src/main/java/com/github/minigithub/service/implementation/LabelApplicationServiceImplementation.java
Labels: enhancement

#59 removed empty lines
  src/main/java/com/github/minigithub/dto/CommentDTO.java
  src/main/java/com/github/minigithub/dto/EventDTO.java
  src/main/java/com/github/minigithub/dto/LabelApplicationDTO.java
  src/main/java/com/github/minigithub/model/Comment.java
  src/main/java/com/github/minigithub/model/Event.java
  src/main/java/com/github/minigithub/model/LabelApplication.java
  src/main/java/com/github/minigithub/repository/CommentRepository.java
  src/main/java/com/github/minigithub/repository/EventRepository.java
  src/main/java/com/github/minigithub/repository/LabelApplicationRepository.java
Labels: invalid

#60 setting gitrepo and developers
  src/main/java/com/github/minigithub/service/implementation/ProjectServiceImplementation.java
Labels: bug

#61 Feature controllers update
  src/main/java/com/github/minigithub/controller/CommentController.java
  src/main/java/com/github/minigithub/controller/EventController.java
  src/main/java/com/github/minigithub/controller/LabelApplicationController.java
Labels: enhancement

#62 user controller
  src/main/java/com/github/minigithub/controller/AuthenticationController.java
  src/main/java/com/github/minigithub/controller/UserController.java
  src/main/java/com/github/minigithub/model/User.java
  src/main/java/com/github/minigithub/repository/UserRepository.java
  src/main/java/com/github/minigithub/service/UserService.java
Labels: enhancement

#63 added history entity
  src/main/java/com/github/minigithub/controller/HistoryController.java
  src/main/java/com/github/minigithub/dto/HistoryDTO.java
  src/main/java/com/github/minigithub/model/History.java
  src/main/java/com/github/minigithub/repository/HistoryRepository.java
  src/main/java/com/github/minigithub/service/HistoryService.java
Labels: enhancement

#66 script updated
  src/main/resources/import.sql
Labels: bug

#67 Fixed branch resource
  src/main/java/com/github/minigithub/controller/BranchController.java
  src/main/java/com/github/minigithub/service/BranchService.java
Labels: bug

#68 Added model
  272200861_454285259751198_9163655989264426853_n.jpg
Labels: configure
