Repository aca24/UKS, pull requests merged in 2022-01, with the labels that each got.

#3 Project initialization
  db.sqlite3
  github/__init__.py
  github/admin.py
  github/apps.py
  github/migrations/__init__.py
  github/models.py
  github/tests.py
  github/views.py
  githubapi/__init__.py
  githubapi/__pycache__/__init__.cpython-310.pyc
  githubapi/__pycache__/settings.cpython-310.pyc
  githubapi/__pycache__/urls.cpython-310.pyc
  githubapi/__pycache__/wsgi.cpython-310.pyc
  githubapi/asgi.py
  githubapi/settings.py
  githubapi/urls.py
  githubapi/wsgi.py
  manage.py
Labels: configure

#5 Initialization of project
  github/__init__.py
  github/admin.py
  github/apps.py
  github/migrations/__init__.py
  github/models.py
  github/tests.py
  github/views.py
  githubapi/__init__.py
  githubapi/__pycache__/__init__.cpython-310.pyc
  githubapi/__pycache__/settings.cpython-310.pyc
  githubapi/asgi.py
  githubapi/settings.py
  githubapi/urls.py
  githubapi/wsgi.py
  manage.py
Labels: configure

#6 Project initialization
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/github/minigithub/MinigithubApplication.java
  src/main/resources/application.properties
  src/main/resources/script.sql
  src/test/java/com/github/minigithub/MinigithubApplicationTests.java
Labels: configure

#13 model creation, connecting model with the database
  pom.xml
  src/main/java/META-INF/MANIFEST.MF
  src/main/java/com/github/minigithub/model/Branch.java
  src/main/java/com/github/minigithub/model/Comment.java
  src/main/java/com/github/minigithub/model/Commit.java
  src/main/java/com/github/minigithub/model/Event.java
  src/main/java/com/github/minigithub/model/GitRepo.java
  src/main/java/com/github/minigithub/model/Issue.java
  src/main/java/com/github/minigithub/model/Label.java
  src/main/java/com/github/minigithub/model/LabelApplication.java
  src/main/java/com/github/minigithub/model/Milestone.java
  src/main/java/com/github/minigithub/model/Project.java
  src/main/java/com/github/minigithub/model/PullRequest.java
  src/main/java/com/github/minigithub/model/Role.java
  src/main/java/com/github/minigithub/model/State.java
  src/main/java/com/github/minigithub/model/StateChange.java
  src/main/java/com/github/minigithub/model/Task.java
  src/main/java/com/github/minigithub/model/User.java
  src/main/resources/application.properties
Labels: configure

#14 added folders and database script
  pom.xml
  src/main/java/com/github/minigithub/controller/TaskController.java
  src/main/java/com/github/minigithub/dto/TaskDTO.java
  src/main/java/com/github/minigithub/mapper/TaskMapper.java
  src/main/java/com/github/minigithub/model/User.java
  src/main/java/com/github/minigithub/repository/TaskRepository.java
  src/main/java/com/github/minigithub/service/TaskService.java
  src/main/resources/application.properties
  src/main/resources/import.sql
Labels: configure

#16 Feature event label application comment cruds
  src/main/java/com/github/minigithub/dto/CommentDTO.java
  src/main/java/com/github/minigithub/dto/EventDTO.java
  src/main/java/com/github/minigithub/dto/LabelApplicationDTO.java
  src/main/java/com/github/minigithub/model/Comment.java
  src/main/java/com/github/minigithub/model/Event.java
  src/main/java/com/github/minigithub/model/LabelApplication.java
  src/main/java/com/github/minigithub/repository/CommentRepository.java
  src/main/java/com/github/minigithub/repository/EventRepository.java
  src/main/java/com/github/minigithub/repository/LabelApplicationRepository.java
  src/main/resources/application.properties
Labels: enhancement

#15 dto classes
  src/main/java/com/github/minigithub/dto/LabelDTO.java
  src/main/java/com/github/minigithub/dto/MilestoneDTO.java
  src/main/java/com/github/minigithub/dto/ProjectDTO.java
Labels: enhancement

#17 repository interfaces
  src/main/java/com/github/minigithub/repository/LabelRepository.java
  src/main/java/com/github/minigithub/repository/MilestoneRepository.java
  src/main/java/com/github/minigithub/repository/ProjectRepository.java
  src/main/java/com/github/minigithub/service/LabelService.java
  src/main/java/com/github/minigithub/service/MilestoneService.java
  src/main/java/com/github/minigithub/service/ProjectService.java
Labels: enhancement

#19 controller classes
  src/main/java/com/github/minigithub/controller/LabelController.java
  src/main/java/com/github/minigithub/controller/MilestoneController.java
  src/main/java/com/github/minigithub/controller/ProjectController.java
Labels: enhancement

#20 crud operations for label
  src/main/java/com/github/minigithub/controller/LabelController.java
  src/main/java/com/github/minigithub/dto/LabelDTO.java
  src/main/java/com/github/minigithub/mapper/LabelMapper.java
  src/main/java/com/github/minigithub/mapper/MilestoneMapper.java
  src/main/java/com/github/minigithub/mapper/ProjectMapper.java
  src/main/java/com/github/minigithub/model/Label.java
  src/main/java/com/github/minigithub/service/LabelService.java
Labels: enhancement

#21 event, labelApplication and comment mappings
  src/main/java/com/github/minigithub/dto/CommentDTO.java
  src/main/java/com/github/minigithub/dto/EventDTO.java
  src/main/java/com/github/minigithub/dto/LabelApplicationDTO.java
  src/main/java/com/github/minigithub/dto/LabelDTO.java
  src/main/java/com/github/minigithub/dto/TaskDTO.java
  src/main/java/com/github/minigithub/mapper/CommentMapper.java
  src/main/java/com/github/minigithub/mapper/EventMapper.java
  src/main/java/com/github/minigithub/mapper/LabelApplicationMapper.java
  src/main/java/com/github/minigithub/model/Comment.java
  src/main/java/com/github/minigithub/model/Event.java
  src/main/java/com/github/minigithub/model/Label.java
  src/main/java/com/github/minigithub/model/LabelApplication.java
  src/main/java/com/github/minigithub/model/Task.java
Labels: enhancement

#22 added constructors for event, labelApplication and comment
  src/main/java/com/github/minigithub/model/Comment.java
  src/main/java/com/github/minigithub/model/Event.java
  src/main/java/com/github/minigithub/model/LabelApplication.java
Labels: enhancement

#23 event, labelApplication and comment service creation
  src/main/java/com/github/minigithub/service/CommentService.java
  src/main/java/com/github/minigithub/service/EventService.java
  src/main/java/com/github/minigithub/service/LabelApplicationService.java
  src/main/java/com/github/minigithub/service/implementation/CommentServiceImplementation.java
  src/main/java/com/github/minigithub/service/implementation/EventServiceImplementation.java
  src/main/java/com/github/minigithub/service/implementation/LabelApplicationServiceImplementation.java
Labels: enhancement

#25 Docker configuration
  .gitignore
  Dockerfile
  docker-compose.yml
  pom.xml
  src/main/resources/application.properties
Labels: configure

#26 Feature event label application comment controllers
  src/main/java/com/github/minigithub/config/WebConfig.java
  src/main/java/com/github/minigithub/controller/CommentController.java
  src/main/java/com/github/minigithub/controller/EventController.java
  src/main/java/com/github/minigithub/controller/LabelApplicationController.java
  src/main/java/com/github/minigithub/dto/CommentDTO.java
  src/main/java/com/github/minigithub/dto/EventDTO.java
  src/main/java/com/github/minigithub/dto/LabelApplicationDTO.java
  src/main/java/com/github/minigithub/mapper/TaskMapper.java
  src/main/java/com/github/minigithub/model/Comment.java
  src/main/java/com/github/minigithub/model/Event.java
  src/main/java/com/github/minigithub/model/LabelApplication.java
  src/main/java/com/github/minigithub/repository/CommentRepository.java
  src/main/java/com/github/minigithub/repository/EventRepository.java
  src/main/java/com/github/minigithub/repository/LabelApplicationRepository.java
  src/main/java/com/github/minigithub/service/CommentService.java
  src/main/java/com/github/minigithub/service/EventService.java
  src/main/java/com/github/minigithub/service/LabelApplicationService.java
  src/main/java/com/github/minigithub/service/implementation/CommentServiceImplementation.java
  src/main/java/com/github/minigithub/service/implementation/EventServiceImplementation.java
  src/main/java/com/github/minigithub/service/implementation/LabelApplicationServiceImplementation.java
  src/main/resources/import.sql
Labels: enhancement

#29 project and milestone crud operations
  src/main/java/com/github/minigithub/MinigithubApplication.java
  src/main/java/com/github/minigithub/controller/MilestoneController.java
  src/main/java/com/github/minigithub/controller/ProjectController.java
  src/main/java/com/github/minigithub/dto/MilestoneDTO.java
  src/main/java/com/github/minigithub/dto/ProjectDTO.java
  src/main/java/com/github/minigithub/mapper/MilestoneMapper.java
  src/main/java/com/github/minigithub/mapper/ProjectMapper.java
  src/main/java/com/github/minigithub/model/Milestone.java
  src/main/java/com/github/minigithub/model/Project.java
  src/main/java/com/github/minigithub/model/User.java
  src/main/java/com/github/minigithub/service/LabelService.java
  src/main/java/com/github/minigithub/service/MilestoneService.java
  src/main/java/com/github/minigithub/service/ProjectService.java
  src/main/resources/import.sql
Labels: enhancement

#31 CRUD: Branch, Commit, User
  src/main/java/com/github/minigithub/controller/BranchController.java
  src/main/java/com/github/minigithub/controller/CommitController.java
  src/main/java/com/github/minigithub/controller/UserController.java
  src/main/java/com/github/minigithub/dto/BranchDTO.java
  src/main/java/com/github/minigithub/dto/CommitDTO.java
  src/main/java/com/github/minigithub/dto/UserDTO.java
  src/main/java/com/github/minigithub/model/Branch.java
  src/main/java/com/github/minigithub/model/Commit.java
  src/main/java/com/github/minigithub/model/User.java
  src/main/java/com/github/minigithub/repository/BranchRepository.java
  src/main/java/com/github/minigithub/repository/CommitRepository.java
  src/main/java/com/github/minigithub/repository/RoleRepository.java
  src/main/java/com/github/minigithub/repository/UserRepository.java
  src/main/java/com/github/minigithub/service/BranchService.java
  src/main/java/com/github/minigithub/service/CommitService.java
  src/main/java/com/github/minigithub/service/RoleService.java
  src/main/java/com/github/minigithub/service/UserService.java
  src/main/resources/import.sql
Labels: enhancement

#28 added constructors for task, user, milestone and for their dto objects
  src/main/java/com/github/minigithub/controller/TaskController.java
  src/main/java/com/github/minigithub/dto/BranchDTO.java
  src/main/java/com/github/minigithub/dto/CommitDTO.java
  src/main/java/com/github/minigithub/dto/EventDTO.java
  src/main/java/com/github/minigithub/dto/MilestoneDTO.java
  src/main/java/com/github/minigithub/dto/StateChangeDTO.java
  src/main/java/com/github/minigithub/dto/TaskDTO.java
  src/main/java/com/github/minigithub/dto/UserDTO.java
  src/main/java/com/github/minigithub/model/Event.java
  src/main/java/com/github/minigithub/model/Milestone.java
  src/main/java/com/github/minigithub/model/Task.java
  src/main/java/com/github/minigithub/model/User.java
  src/main/java/com/github/minigithub/service/TaskService.java
  src/main/java/com/github/minigithub/service/implementation/StateChangeServiceImplementation.java
  src/main/java/com/github/minigithub/service/implementation/TaskServiceImplementation.java
  src/main/resources/import.sql
Labels: enhancement

#33 Create workflow maven.yml
  .github/workflows/maven.yml
Labels: devops

#36 Added deployment action
  .github/workflows/heroku.yml
  system.properties
Labels: devops

#30 service interfaces and implementation separated
  src/main/java/com/github/minigithub/mapper/MilestoneMapper.java
  src/main/java/com/github/minigithub/model/State.java
  src/main/java/com/github/minigithub/service/LabelService.java
  src/main/java/com/github/minigithub/service/MilestoneService.java
  src/main/java/com/github/minigithub/service/ProjectService.java
  src/main/java/com/github/minigithub/service/implementation/LabelServiceImplementation.java
  src/main/java/com/github/minigithub/service/implementation/MilestoneServiceImplementation.java
  src/main/java/com/github/minigithub/service/implementation/ProjectServiceImplementation.java
Labels: enhancement

#40 event, labelApplication, comment refactoring and call of new entities
  src/main/java/com/github/minigithub/controller/CommentController.java
  src/main/java/com/github/minigithub/controller/EventController.java
  src/main/java/com/github/minigithub/controller/LabelApplicationController.java
  src/main/java/com/github/minigithub/dto/CommentDTO.java
  src/main/java/com/github/minigithub/dto/EventDTO.java
  src/main/java/com/github/minigithub/dto/LabelApplicationDTO.java
  src/main/java/com/github/minigithub/model/Comment.java
  src/main/java/com/github/minigithub/model/Event.java
  src/main/java/com/github/minigithub/model/LabelApplication.java
  src/main/java/com/github/minigithub/service/CommentService.java
  src/main/java/com/github/minigithub/service/EventService.java
  src/main/java/com/github/minigithub/service/LabelApplicationService.java
  src/main/java/com/github/minigithub/service/implementation/CommentServiceImplementation.java
  src/main/java/com/github/minigithub/service/implementation/EventServiceImplementation.java
  src/main/java/com/github/minigithub/service/implementation/LabelApplicationServiceImplementation.java
  src/main/resources/import.sql
Labels: enhancement
